[[language]]
name = "python"
auto-format = true
formatter = { command = "bash", args = ["-c", "isort - | ruff format --silent -"] }
scope = "source.python"

[language-server.pylsp.config.pylsp.plugins]
rope_autoimport = {enabled = true}

[[language]]
name = "elixir"
auto-format = true

[[language]]
name = "html"
auto-format = true
formatter = { command = 'prettier', args = ["--parser", "html"] }
